config/routes.rb
Sombrero::Application.routes.draw do
  resources :polls do
    member do
      put :vote
    end
  end
  resource :votes

  get 'home', to: 'cameras#splash', as: 'index'
  root 'cameras#splash'

  get 'inside', to: 'pages#inside', as: 'inside'
  
  resource :search do 
    get :solr
  end

  resources :cameras do
    collection do
      get :compare
      get :splash
      get :top_cameras
      post :compare_cameras
    end
    member do
      get :sample_images
    end
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks'}
  
  namespace :admin do
    root 'base#index'
    resources :users
  end  

   get '*a', :to => 'errors#routing'
end

app/models/poll.rb
# The model for polls
class Poll < ActiveRecord::Base
  belongs_to :user
  serialize :products, JSON
  serialize :image_urls, Array
  serialize :title, Array
  has_many :votes

  scope :active, -> { where(status: "active") }
  before_create {|p| p.status = 'active'}

  def editable_by_user user
  	user.admin || (self.status == 'active' && self.user == user)
  end

  def viewable_by_user user
  	user.admin || self.status == 'active'
  end

  def self.update_vote_count(upc_code, poll_id, user_id)
    if Vote.where(poll_id: poll_id, user_id: user_id).count == 0
      p = Poll.find poll_id
      p.products[upc_code] += 1
      p.save!
      Vote.create(poll_id: poll_id, upc_code: upc_code, user_id: user_id)
      p.products[upc_code]
    end
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :all 

  # GET /polls
  # GET /polls.json
  def index
    # http://localhost:3000/polls.json?user_email=admin@example.com&user_token=myTSJyjBG2WzdWrMbGD3&my_polls=true&available_for_voting=true
    @polls = if params[:my_polls].present?
      current_user.polls
    else
      Poll.active
    end
    @polls -= current_user.polls_voted_for if params[:available_for_voting].present?
    return @polls
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
    @poll = Poll.find(params[:id])
    if !@poll.viewable_by_user(current_user)
      render :status=>400,
      :json => { :message=>"You cannot view this poll." }
    else
      respond_to do |format|
        format.html
        format.json { render json: @poll }
      end
    end
  end

  # GET /polls/new
  def new
    @poll = current_user.polls.new
  end

  # GET /polls/1/edit
  def edit
    if !@poll.editable_by_user(current_user)
      render :status=>400,
      :json => { :message=>"You cannot edit this poll." }
      return
    end
  end

  # POST /polls
  # POST /polls.json
  def create
    # data : {"poll":{"question":"weqwe", "products":"qewqw", "user_id":"1"}}
    # http://localhost:3000/polls.json?user_email=admin@example.com&user_token=myTSJyjBG2WzdWrMbGD3
    received_params={}
    received_params["question"] = poll_params[:question]
    received_params["image_urls"] = poll_params[:image_urls]
    received_params["title"] = poll_params[:title]
    received_params["products"] = {}
    poll_params[:products].map { |x| received_params["products"][x]=0 }

    @poll = current_user.polls.new(received_params)
    
    respond_to do |format|
      if @poll.save
        format.html { redirect_to polls_url, notice: 'Poll was successfully created.'}
        format.json { render json: "Success".to_json, :status => 200 }
      else
        format.html { render action: 'new' }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url }
      format.json { head :no_content }
    end
  end

  def default_serializer_options
    {root: false}
  end

  # Update votecount
  def vote
    product_id,poll_id  = params[:UPC],params[:id]
    vote_count = Poll.update_vote_count(product_id,poll_id,current_user.id)
    if vote_count
      render :status => 200, :json => { :count => vote_count }
    else
      render :status => 422, :json => { :message=>"You have voted for this poll earlier." }
    end
  end
    
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:user_id, :question, :image_urls => [], :title => [], :products => [])
    end

end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :products %><br>
    <%= f.text_field :products %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :image_urls %><br>
    <%= f.text_field :image_urls %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/polls/_form.mobile.erb
<%= form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xs-12 poll-new-question">
      <%= f.text_area :question, placeholder: "Your question goes here..." %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <a class="poll-new-products">
        Add a Product
      </a>
    </div>
    <div class="col-xs-12">
      <a class="poll-new-products">
        Add a Product
      </a>
    </div>
    <div class="col-xs-12">
      <a class="poll-new-products">
        Add a Product
      </a>
    </div>
    <div class="col-xs-12">
      <a class="poll-new-products">
        Add a Product
      </a>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div>
        <button id="create-poll" class="btn btn-block btn-info clearlee-button">Ask</button>
        <%= link_to 'Cancel', polls_path, class: "btn btn-block btn-info clearlee-button" %>
      </div>
    </div>
  </div>
<% end %>

app/views/polls/edit.html.erb
<h1>Editing poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/edit.mobile.erb
<h1>Editing poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<h1>Listing polls</h1>

<table>
  <thead>
    <tr>
      <th>Products</th>
      <th>User</th>
      <th>Question</th>
      <th>Image Urls</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= poll.products %></td>
        <td><%= poll.user_id %></td>
        <td><%= poll.question %></td>
        <td><%= poll.image_urls %></td>
        <td><%= link_to 'Show', poll %></td>
        <td><%= link_to 'Edit', edit_poll_path(poll) %></td>
        <td><%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poll', new_poll_path %>

app/views/polls/index.mobile.erb
<% title("Polls") %>

<%= link_to 'New Poll', new_poll_path, class: "btn btn-block btn-info clearlee-button" if user_signed_in? %>

<% @polls.each do |poll| %>
  <%= link_to poll do %>
    <div class="row poll-display">
      <p><%= poll.question %></p>
      <% poll.products.each do |k,v| %>
        <div class="col-xs-3">
          <%= v %>
        </div>
      <% end %>
      <% poll.image_urls.each do |image| %>
        <div class="col-xs-3">
          <img src=<%= image %>>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/polls/new.html.erb
<h1>New poll</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/polls/new.mobile.erb
<% title("New poll") %>

<div class="poll-show">
  <%= form_for(@poll) do |f| %>
    <% if @poll.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

        <ul>
        <% @poll.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col-xs-12 poll-new-question">
        <%= f.text_area :question, placeholder: "Your question goes here..." %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 poll-new-products">
        <a class="fill-div poll-new-products-click-to-add">
          Add a Product
        </a>
      </div>
      <div class="col-xs-12 poll-new-products">
        <a class="fill-div poll-new-products-click-to-add">
          Add a Product
        </a>
      </div>
      <div class="col-xs-12 poll-new-products">
        <a class="fill-div poll-new-products-click-to-add">
          Add a Product
        </a>
      </div>
      <div class="col-xs-12 poll-new-products">
        <a class="fill-div poll-new-products-click-to-add">
          Add a Product
        </a>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col-xs-12">
      <div>
        <button id="create-poll" class="btn btn-block btn-info clearlee-button">Ask</button>
        <%= link_to 'Cancel', polls_path, class: "btn btn-block btn-info clearlee-button" %>
      </div>
    </div>
  </div>
</div>

<div class="search-to-vote hidden">
  <p><input autofocus="autofocus" class="form-control" id="search-category" type="text" value="" placeholder="Brand" /></p>
  <p><input class="form-control" id="search-name" type="text" value="" placeholder="Model" /></p>
  <p><button id="search-bby" class="btn btn-block btn-info clearlee-button">Search</button></p>
  <div class="results"></div>
</div>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @poll.question %>
</p>

<p>
  <strong>Products:</strong>
  <%= @poll.products %>
</p>

<p>
  <strong>Image urls:</strong>
  <%= @poll.image_urls.keys %>
</p>

<p>
  <strong>Product Title:</strong>
  <%= @poll.title.keys %>
</p>

<p>
  <strong>User:</strong>
  <%= @poll.user_id %>
</p>

<%= link_to 'Edit', edit_poll_path(@poll) %> |
<%= link_to 'Back', polls_path %>

app/views/polls/show.mobile.erb
<p id="notice"><%= notice %></p>
<div id="poll-id" class="hidden"><%= @poll.id%></div>
<div class="row">
  <div class="col-xs-12 poll-show-question">
    <p><%= @poll.question %></p>
    <small><p class="poll-user-name"><%= User.find(@poll.user_id).username %></p></small>
  </div>
</div>

<% @poll.image_urls.each_with_index do |image,index| %>
  <div class="row">
   <a class="fill-div poll-show-products">
    <div class="col-xs-2">
    <div id="product-code" class=<%= @poll.products.keys[index]%>></div>
      <img src=<%= image %>>
    </div>
    <div class="col-xs-8 poll-product-title">
      <%= @poll.title[index].gsub('System Camera with','') %>
    </div>
    <div class="col-xs-2 text-center vote-count">
      <%= @poll.products.values[index] %>
    </div>
    </a>
  </div>
<% end %>

<div>
  <button id="vote" class="btn btn-block btn-info clearlee-button">Vote</button>
  <%= link_to 'Cancel', polls_path, class: "btn btn-block btn-info clearlee-button" %>
</div>