config/routes.rb
Sombrero::Application.routes.draw do
  resources :polls do
    member do
      put :vote
    end
  end
  resource :votes

  get 'home', to: 'cameras#splash', as: 'index'
  root 'cameras#splash'

  get 'inside', to: 'pages#inside', as: 'inside'
  
  resource :search do 
    get :solr
  end

  resources :cameras do
    collection do
      get :compare
      get :splash
      get :top_cameras
      post :compare_cameras
    end
    member do
      get :sample_images
    end
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks'}
  
  namespace :admin do
    root 'base#index'
    resources :users
  end  

   get '*a', :to => 'errors#routing'
end

app/models/user.rb
# The user model
class User < ActiveRecord::Base
  has_many :polls
  has_many :votes
  acts_as_token_authenticatable
  # Use friendly_id on Users
  extend FriendlyId
  friendly_id :friendify, use: :slugged
  
  # necessary to override friendly_id reserved words
  def friendify
    if username.downcase == "admin"
      "user-#{username}"
    else
      "#{username}"
    end
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  devise :omniauthable, :omniauth_providers => [:facebook, :twitter, :google_oauth2]
         
  # Pagination
  paginates_per 100
  
  # Validations
  # :username
  validates :username, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /\A[a-zA-Z0-9]*\z/, on: :create, message: "can only contain letters and digits"
  validates :username, length: { in: 4..10 }
  # :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  # For user Pagination.
  def self.paged(page_number)
    order(admin: :desc, username: :asc).page page_number
  end
  
  # Search for a user through the pages
  def self.search_and_order(search, page_number)
    if search
      where("username LIKE ?", "%#{search.downcase}%").order(
      admin: :desc, username: :asc
      ).page page_number
    else
      order(admin: :desc, username: :asc).page page_number
    end
  end

  # Get the list of last n signed_up users
  #
  # @param count [Integer]
  # @return [Array] aray of n signed up users
  def self.last_signups(count)
    order(created_at: :desc).limit(count).select("id","username","slug","created_at")
  end
  
  # Get the list of last n signed_in users
  #
  # @param count [Integer]
  # @return [Array] aray of n signed in users
  def self.last_signins(count)
    order(last_sign_in_at: 
    :desc).limit(count).select("id","username","slug","last_sign_in_at")
  end
  
  # Returns the total count of active user (except admin and those locked)
  # @return [Integer] count of active users
  def self.users_count
    where("admin = ? AND locked = ?",false,false).count
  end

  # handle facebook omniauth
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  # handle omniauth
  def self.from_omniauth(auth)
    if user = User.find_by_email(auth.info.email)
      user.provider = auth.provider
      user.uid = auth.uid
      user
    else
      where(auth.slice(:provider, :uid)).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.username = auth.info.name
        user.email = auth.info.email
        user.avatar = auth.info.image
      end
    end
  end

  # handle facebook omniauth - create a user logged in through facebook
  def self.find_for_facebook_oauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      user.save!
    end
  end

  def polls_voted_for
    self.votes.map(&:poll)    
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [
    :show,
    :edit,
    :update,
    :destroy
  ]

  def index
    @users = User.search_and_order(params[:search], params[:page])
  end
  
  def show
    redirect_to edit_admin_user_path(params[:id])
  end
  
  def edit
  end
  
  def update
    old_username = @user.username
    new_params = user_params.dup
    new_params[:username] = new_params[:username].strip
    new_params[:email] = new_params[:email].strip
    
    @user.username = new_params[:username]
    @user.email = new_params[:email]
    @user.password = new_params[:password] if new_params[:password].strip.length > 0
    @user.password_confirmation = new_params[:password_confirmation] if new_params[:password_confirmation].strip.length > 0
    
    if current_user.id != @user.id
      @user.admin = new_params[:admin]=="0" ? false : true
      @user.locked = new_params[:locked]=="0" ? false : true
    end
    
    if @user.valid?
      @user.skip_reconfirmation!
      @user.save
      redirect_to admin_users_path, notice: "#{@user.username} updated."
    else
      flash[:alert] = "#{old_username} couldn't be updated."
      render :edit
    end
  end
  
  
  private 
  
  def set_user
    @user = User.friendly.find(params[:id])
  rescue
    flash[:alert] = "The user with an id of #{params[:id]} doesn't exist."
    redirect_to admin_users_path
  end
  
  def user_params
    params.require(:user).permit(
    :username,
    :email,
    :password,
    :password_confirmation,
    :admin,
    :uid,
    :locked
    )
  end
  
end

app/views/admin/users/edit.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>
      Edit User <small><%= "#{@user.username.capitalize} - id: #{@user.id}" %></small>
    </h1>
    <p><%= link_to "Back to Users", admin_users_path %></p>

    <%= form_for [:admin, @user], :html => { :role => "form" } do |f| %>
    
    <div class="form-group">
      <%= f.label :username %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.text_field :username, :autofocus => true, class: "form-control" %>  
        </div>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :email %>
      <div class="row">
        <div class="col-sm-6">      
          <%= f.email_field :email, class: "form-control" %>  
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>
    </div>
    
    <% unless current_user.id == @user.id %>
    <div class="checkbox">
      <%= f.check_box :locked %> <%= f.label :locked, "Is Locked?" %>
    </div>
    
    <div class="checkbox">
      <%= f.check_box :admin %> <%= f.label :admin, "Is Admin?" %>
    </div>    
    <% end %>

    <div class="row">
      <div class="col-sm-6">
        <%= f.submit "Update User", class: "btn btn-danger" %>
      </div>
    </div>    
    
    <% end %>

  </div>
</div>

app/views/admin/users/index.html.erb
<h1>Users <small>Admin</small></h1>
<p><%= link_to "Back to Admin", admin_root_path %></p>

<div class="text-center">
  <p><%= page_entries_info @users %></p>
  <%= paginate @users %>
</div>

<%= form_tag admin_users_path, method: 'get', html: {role: "form"} do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
    <%= link_to "All", admin_users_path, {class: "btn btn-sm btn-link"} %>
  </p>
<% end %>

<table class="table table-striped">
  <tr>
    <th>User ID</th>
    <th>Username</th>
    <th>Admin</th>
    <th>Locked</th>
    <th>Email</th>
    <th>Sign In Count</th>
    <th>Created At</th>
    <th>Last Sign In</th>
    <th>Last Sign In IP</th>
  </tr>
  
  <% @users.each do |user| %>
  
  <tr>
    <td><%= user.id %></td>
    <td><%= link_to user.username.capitalize, admin_user_path(user) %></td>
    <td><%= user.admin? ? "<b>yes</b>".html_safe : "no" %></td>
    <td><%= user.locked? ? "<b>yes</b>".html_safe : "no" %></td>
    <td><%= user.email %></td>
    <td><%= user.sign_in_count %></td>
    <td><%= time_ago_in_words(user.created_at) %></td>
    <% unless user.last_sign_in_at.nil? %>
    <td><%= time_ago_in_words(user.last_sign_in_at)%> ago</td>
    <% else %>
    <td>never</td>
    <% end %>
    <td><%= user.last_sign_in_ip %></td>
  </tr>
  
  <% end %>
  
</table>

<div class="text-center">
  <p><%= page_entries_info @users %></p>
  <%= paginate @users %>
</div>