config/routes.rb
Sombrero::Application.routes.draw do
  resources :polls do
    member do
      put :vote
    end
  end
  resource :votes

  get 'home', to: 'cameras#splash', as: 'index'
  root 'cameras#splash'

  get 'inside', to: 'pages#inside', as: 'inside'
  
  resource :search do 
    get :solr
  end

  resources :cameras do
    collection do
      get :compare
      get :splash
      get :top_cameras
      post :compare_cameras
    end
    member do
      get :sample_images
    end
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks'}
  
  namespace :admin do
    root 'base#index'
    resources :users
  end  

   get '*a', :to => 'errors#routing'
end

app/views/layouts/_footer.html.erb
<footer>
	<span class="proxima-nova-regular">
		<a href="http://www.netbramha.com/" title="netbrahma studios">designed by 
			<%= image_tag 'logo-netbrahma-studios.png', width: "90", height: "32", alt: "netbrahma studios" %>
		</a>
	</span>
</footer>

app/views/layouts/_footer.mobile.erb
<div id="footer">
  <div class="container">
    <div class="col-xs-12 text-center">
      <p><small>&copy; 2014 - Clearlee!</small></p>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_messages.mobile.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- <header class="row">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-asterisk"></span></a>
    </div>
    <div class="collapse navbar-collapse" id="collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>  
      </ul> 
    </div>
   </nav>
</header>
 -->

app/views/layouts/_navigation.mobile.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
      <div class="navbar-header">
        <%= link_to "", root_url(:mobile => 1), :class => "fa fa-home nav-bar-icons-home nav-bar-icons-back navbar-left" %>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <%= render 'layouts/navigation_links' %>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<div class="collapse navbar-collapse">
  <ul class="nav navbar-nav navbar-right">
    <% if !user_signed_in? %>
      <li><%= link_to "Sign in", new_user_session_path %></li>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
    <% else %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Protected Page", inside_path %></li>
          <li><%= link_to "Edit your account", edit_user_registration_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Sign out", destroy_user_session_path, data:{method: :delete} %></li>
          <% if current_user.admin? %>
          <li><%= link_to "Admin", admin_root_path %></li>
          <% end %>
        </ul>
      </li>
    <% end %>
    <li><%= link_to "Reviews", new_user_session_path %></li>
    <li><a href="#pros-cons">Pros & Cons</a></li>
    <li><a href="#specs">Specs</a></li>
  </ul>
  <%= form_tag '/search/solr', :method => :get, :class => "navbar-form navbar-left right-inner-addon", :role => "search" do %>
    <div class="form-group">
      <i class="icon-search"></i>
      <%= search_field_tag :term, params[:term], :class => "input-large ui-widget form-control", :placeholder => "Search" %>
    </div>
  <% end %> 
</div>

<script type="text/javascript">
  jQuery(document).ready(function($) {
    $('input#term').autocomplete({
      minLength: 1,
      source: '<%= solr_search_path(:json) %>',
      mustMatch : false,
      focus: function(event, ui){
        $('input#term').val(ui.item.model_name);
        return false;
      },
      select: function(event, ui){
        $('input#term').val(ui.item.model_name);
        $('.navbar-form').submit(); 
        return false;
      },
    })
    .data("ui-autocomplete")._renderItem = function(ul,item){
                        ul.addClass('search-container');
      return $("<li></li>")
      .data("ui-autocomplete-item",item)
      .append("<a href=/cameras/" + item.id + ">" +"<span class='search-image'><img src='" + 
                   item.default_image_url +"'></span>"  + "<span class='search-model-name'>" + item.model_name  +  "</span></a>" )
      .appendTo(ul);
    };
$('.ui-autocomplete').wrap('<div class="search-wrap" />');
  });
</script>

app/views/layouts/_navigation_links.mobile.erb
<li><%= link_to "Polls", polls_path %></li>

<% if user_signed_in? %>
  <li><%= link_to "Edit Account", edit_user_registration_path %></li>
<% end %>

<% if !user_signed_in? %>
  <li><%= link_to "Sign in", new_user_session_path %></li>
  <li><%= link_to "Sign up", new_user_registration_path %></li>
<% else %>
  <li><%= link_to "Protected Page", inside_path %></li>
  <li><%= link_to "Sign out", destroy_user_session_path, data:{method: :delete} %></li>
<% end %>

<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to "Admin", admin_root_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "Clearlee" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= stylesheet_link_tag "bootstrap", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "bootstrap", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "clearlee", media: "all", "data-turbolinks-track" => true %>
</head>
<body>

<%= yield %>

  
<%= render 'layouts/footer' %>    

</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "Clearlee" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag "application_mobile", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application_mobile", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
      
    <div class="container">
       
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>     
      </div>  
      
    </div>
  </div>
    
  <%= render 'layouts/footer' %>    

</body>
</html>